import React from 'react';
import ArticleDisplay from '../../components/ArticleDisplay';

export default function NiharikaBhattacharjee2021Disp(props) {
    return (
        <ArticleDisplay title="Automated Dental Cavity Detection System Using Artificial Intelligence" author="Niharika Bhattacharjee" tag="Medicine" image="../logo512.png" year="2021" id="niharika_bhattacharjee">
            It all started when I thought I had gingivitis. I came to this conclusion after consulting the most reputable source I knew, webmd.com of course. Sitting at the doctor's office, I anxiously waited for the confirmation. Were my suspicions correct? Nope! As my doctor explained my negative result, guilt slowly overcame me. I had just wasted three hours of my dad's time. Driving home, I was determined to find meaning in this seemingly unfulfilling trip, and indeed I did. The visit highlighted my privilege, which ignited my "eureka" moment. A dental diagnosis requires time, a medical professional, and money. Three things millions of people globally don't have; a problem I sought to address. With the aim of increasing dental care worldwide, I invested the following two years in creating an automated dental cavity detection system using Artificial Intelligence (AI). With a single dental photographic color image, my system can provide a cavity diagnosis and explain the diagnosis to the end-user in an understandable manner. By automating detection and explainability, which are skills dentists typically employ, I hope to assist those who can't visit the dentist due to lack of dental insurance, dentophobia, or limited dentist availability. Through this research, I had the opportunity to work with an IBM researcher and experiment with different deep learning architectures, explainable AI algorithms, and training techniques such as curriculum learning and transfer learning. By incorporating deep learning into my project, I gained experience in an interdisciplinary field powered by linear algebra, calculus, statistics, and biology. Above all, conducting such research has motivated me to pursue a career in computational health.
        </ArticleDisplay>
    )
}