import React from 'react';
import ArticleDisplay from '../../components/ArticleDisplay';

export default function SathvikNallamalli2021Disp(state) {
    return (
    <ArticleDisplay title="Portable Machine-Learning Based Sensor of Respiratory Illnesses" author="Sathvik Nallamalli" tag="Medicine" image="../logo512.png" year="2021" id="sathvik_nallamalli" >
        Lung cancer is the leading cause of cancer-related deaths in the world and succeeding melanoma skin cancer, it is the second leading cancer in men and women. Accessibility to the expensive imaging technology and accurate diagnostic tools for this disease is limited and therefore leads to death at an early stage. The need exists to develop an innovative diagnostic and detection measure to promptly detect the presence and type of cancer. This sparked the interest to develop an innovative lung cancer detection algorithm, LCDetect. It uses Python scripts, machine learning models, segmentation algorithms, and localization of solitary pulmonary nodules (SPN's), tumors, and lesions to detect the presence of cancer, malignity, type and stage. It uses the lung CT scan to provide a thorough diagnosis and reduce the need for PET and biopsy to prevent late detection. The algorithm works in three modules; image preprocessing, image detection, and a convolutional neural network model (CNN). Preprocessing includes noise removal, normalization, image filters, segmentation and augmentation. Extracted regions of interest, that are based on the location of nodules, are passed to image detection for feature extraction through segmentation and pixel calculations. Based on the extracted features, the layers of the CNN categorize the lung cancer using location-based analysis. Through the complex image detection and preprocessing techniques that feed through the layers of CNN model, the generated feature maps perform this classification. After several optimization techniques such as backpropagation and regression, a thorough statistical analysis was performed. Then, the algorithm was deployed on Azure Web Services. The system was trained and tested across 50,000 datasets and patient CT scans from local radiologists. The final algorithm passed with an accuracy of 98%. LCDetect is an innovative and fully functional solution to accurately detect for adenocarcinoma, squamous cell, non-small cell, and small cell lung cancer and predict the stage.
    </ArticleDisplay>
    )
}